version: '3.8'

services:
  sales-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data.db:/app/data.db:ro  # Mount database as read-only
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s